[build]
  base = "frontend"
  command = "GENERATE_SOURCEMAP=false DISABLE_ESLINT_PLUGIN=true CI=false npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --no-fund"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
